// Builds blocks/vendor/: Blockly (the "blockly" devDependency, Apache-2.0)
// bundled by esbuild into one minified ES module, plus the few media files
// Blockly's own CSS and controls load (cursors, the zoom and trash can
// sprites). The click sounds are left out: the page turns sounds off.
// Run after upgrading blockly: npm install && npm run build:blockly.
import { build } from 'esbuild';
import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync } from 'node:fs';
import { dirname, extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const lib = join(ROOT, 'node_modules', 'blockly');
const out = join(ROOT, 'blocks', 'vendor');
const { version } = JSON.parse(readFileSync(join(lib, 'package.json'), 'utf-8'));

rmSync(out, { recursive: true, force: true });
mkdirSync(join(out, 'media'), { recursive: true });

await build({
  entryPoints: [join(ROOT, 'blocks', 'vendor-src', 'blockly.js')],
  outfile: join(out, 'blockly.js'),
  bundle: true,
  format: 'esm',
  minify: true,
  legalComments: 'eof',
  logLevel: 'warning',
  banner: {
    js: `/* Blockly ${version} (Apache-2.0, Copyright Google LLC, https://github.com/RaspberryPiFoundation/blockly)`
      + ' bundled by esbuild - generated by npm run build:blockly, do not edit. Licence: see THIRD_PARTY_NOTICES.md */'
  }
});

for (const name of readdirSync(join(lib, 'media')))
{
  if (extname(name) !== '.mp3')
  {
    copyFileSync(join(lib, 'media', name), join(out, 'media', name));
  }
}

const size = statSync(join(out, 'blockly.js')).size;
console.log(`blocks/vendor/: Blockly ${version}, blockly.js ${(size / 1024).toFixed(0)} KB`);
